/**
 * Highly compressed (maximally rotationally symmetric) Hamilton cycle of the
 * permutahedron Πₙ, following:
 *
 *   P. Gregor, A. Merino, T. Mütze,
 *   "The Hamilton Compression of Highly Symmetric Graphs",
 *   Annals of Combinatorics 28 (2024) 379–437.  (Section 5)
 *
 * Πₙ is the Cayley graph of Sₙ generated by adjacent transpositions: vertices
 * are permutations of [n] in one-line notation, edges swap two neighboring
 * entries. The classical Steinhaus–Johnson–Trotter Gray code (our existing
 * "permutohedron" preset) draws with only 3-fold symmetry for n ≥ 5.
 *
 * Here we build a Hamilton cycle whose drawing on a circle has k-fold rotational
 * symmetry with k as large as the construction of Theorem 5.5(i) allows, namely
 * the maximum lcm over partitions of n into pairwise-coprime ODD parts (a₁ ≥ 3),
 * which equals Landau's odd variant λ₀(n). For n ≤ 11 this is the maximum the
 * paper's general construction guarantees (λ₀(n) ≥ λ₂(n)). The realized
 * compression factor per n (3 ≤ n ≤ 10):
 *
 *     n :  3   4   5   6   7   8    9    10
 *     k :  3   3   5   5   7  15   15    21
 *
 * Construction outline (Theorem 5.5(i)):
 *   • Pick a composition a = (a₁,…,a_m) of n into pairwise-coprime odd parts,
 *     a₁ ≥ 3, maximizing lcm(a) = k.
 *   • The automorphism f_a relabels values cyclically within each block
 *     A_i = {b_i+1,…,b_i+a_i}; it has order k and all orbits have size k.
 *   • Lemma 5.4 builds a path Q through one representative of every orbit (with
 *     the block pattern fixed to id(a)), from the identity to a neighbor of
 *     f_a(id). Its base/step rely on Hamilton-laceable paths in small
 *     sub-permutahedra (Tchuente, Theorem 2.4).
 *   • Theorem 5.5 "mixes" Q with a Hamilton path (m = 2, Theorem 2.5) or cycle
 *     (m ≥ 3, Theorem 2.6) of the multiset-permutation graph G(a) to obtain a
 *     path P that visits one vertex per orbit, and the full cycle is
 *     C = P, f_a(P), …, f_a^{k-1}(P).
 *
 * The cited Hamiltonicity results (Theorems 2.4/2.5/2.6) are realized here by
 * small backtracking searches: every auxiliary graph that is searched stays
 * tiny (≤ 720 vertices) regardless of n, so the construction scales to n = 10
 * even though the final cycle has up to 10! = 3,628,800 vertices.
 */

export type IntPerm = number[];

function factorial(n: number): number {
  let r = 1;
  for (let i = 2; i <= n; i++) r *= i;
  return r;
}

function gcd(a: number, b: number): number {
  while (b) [a, b] = [b, a % b];
  return a;
}

function lcm(values: number[]): number {
  return values.reduce((acc, v) => (acc / gcd(acc, v)) * v, 1);
}

function permKey(p: ArrayLike<number>): string {
  let s = "";
  for (let i = 0; i < p.length; i++) s += String.fromCharCode(p[i] + 1);
  return s;
}

/* --------------------------- composition choice --------------------------- */

/**
 * The composition of n into pairwise-coprime odd parts (largest part ≥ 3) that
 * maximizes lcm — i.e. λ₀(n), the maximum order of an odd-cycle-type element of
 * Sₙ. Parts are returned in descending order. Returns null for n < 3.
 */
export function bestOddCoprimeComposition(n: number): number[] | null {
  if (n < 3) return null;
  let best: number[] | null = null;
  let bestLcm = 0;

  // Enumerate partitions into distinct... actually pairwise-coprime odd parts.
  // We search partitions into odd parts and keep those that are pairwise coprime
  // with maximum lcm. Parts chosen in non-increasing order.
  const parts: number[] = [];
  const search = (remaining: number, maxPart: number): void => {
    if (remaining === 0) {
      if (parts.length === 0 || parts[0] < 3) return;
      // pairwise coprime?
      for (let i = 0; i < parts.length; i++) {
        for (let j = i + 1; j < parts.length; j++) {
          if (gcd(parts[i], parts[j]) !== 1) return;
        }
      }
      const l = lcm(parts);
      if (l > bestLcm) {
        bestLcm = l;
        best = parts.slice();
      }
      return;
    }
    for (let p = Math.min(maxPart, remaining); p >= 1; p--) {
      if (p % 2 === 0) continue; // odd parts only
      parts.push(p);
      search(remaining - p, p);
      parts.pop();
    }
  };
  search(n, n);
  return best;
}

/** The compression factor k = λ₀(n) realized for the given n (k = 2 at n = 2). */
export function permutahedronCompressionFactor(n: number): number {
  if (n <= 1) return 1;
  if (n === 2) return 2;
  const a = bestOddCoprimeComposition(n);
  return a ? lcm(a) : 1;
}

/* ------------------------- adjacency / parity utils ----------------------- */

/** Adjacent-transposition neighbors of a permutation (swap each neighbor pair). */
function adjacentNeighbors(p: IntPerm): IntPerm[] {
  const out: IntPerm[] = [];
  for (let i = 0; i + 1 < p.length; i++) {
    const q = p.slice();
    const t = q[i];
    q[i] = q[i + 1];
    q[i + 1] = t;
    out.push(q);
  }
  return out;
}

/** Multiset-adjacent neighbors: swap adjacent positions holding distinct labels. */
function distinctAdjacentNeighbors(p: IntPerm): IntPerm[] {
  const out: IntPerm[] = [];
  for (let i = 0; i + 1 < p.length; i++) {
    if (p[i] === p[i + 1]) continue;
    const q = p.slice();
    const t = q[i];
    q[i] = q[i + 1];
    q[i + 1] = t;
    out.push(q);
  }
  return out;
}

/** All permutations of the given (distinct) values, in lexicographic order. */
function permutationsOf(values: number[]): IntPerm[] {
  if (values.length <= 1) return [values.slice()];
  const out: IntPerm[] = [];
  const used = new Array<boolean>(values.length).fill(false);
  const cur: number[] = [];
  const rec = (): void => {
    if (cur.length === values.length) {
      out.push(cur.slice());
      return;
    }
    for (let i = 0; i < values.length; i++) {
      if (used[i]) continue;
      used[i] = true;
      cur.push(values[i]);
      rec();
      cur.pop();
      used[i] = false;
    }
  };
  rec();
  return out;
}

/* ----------------------- generic Hamilton path search --------------------- */

/** Build the integer adjacency lists for a vertex list and a neighbor function. */
function buildAdjacency(
  vertices: IntPerm[],
  neighborsOf: (p: IntPerm) => IntPerm[]
): { adj: number[][]; index: Map<string, number> } {
  const index = new Map<string, number>();
  for (let i = 0; i < vertices.length; i++) index.set(permKey(vertices[i]), i);
  const adj = vertices.map((v) =>
    neighborsOf(v)
      .map((q) => index.get(permKey(q)))
      .filter((x): x is number => x !== undefined)
  );
  return { adj, index };
}

/**
 * Backtracking search for a Hamilton path (`cycle = false`, from `startIdx` to
 * `endIdx`) or Hamilton cycle (`cycle = true`, closing back on `startIdx`) over
 * an integer adjacency list. Uses a Warnsdorff ordering plus dead-end / degree
 * pruning (no unvisited vertex may become isolated; at most two may drop to a
 * single remaining connection), which keeps the auxiliary searches fast.
 * Returns the vertex-index order, or null if none exists.
 */
function runSearch(
  adj: number[][],
  startIdx: number,
  endIdx: number,
  cycle: boolean
): number[] | null {
  const total = adj.length;
  if (total === 1) return [startIdx];

  const visited = new Uint8Array(total);
  const avail = new Int32Array(total);
  for (let v = 0; v < total; v++) avail[v] = adj[v].length;
  const startNeighbor = new Uint8Array(total);
  for (const w of adj[startIdx]) startNeighbor[w] = 1;

  const order: number[] = [];
  let visitedCount = 0;

  const mark = (u: number): void => {
    visited[u] = 1;
    visitedCount++;
    for (const w of adj[u]) if (!visited[w]) avail[w]--;
  };
  const unmark = (u: number): void => {
    visited[u] = 0;
    visitedCount--;
    for (const w of adj[u]) if (!visited[w]) avail[w]++;
  };

  const stack = new Int32Array(total);

  const feasible = (u: number): boolean => {
    const remaining = total - visitedCount;
    if (remaining <= 1) return true;
    let deg1 = 0;
    let startReach = 0;
    for (let v = 0; v < total; v++) {
      if (visited[v]) continue;
      const d = avail[v];
      if (d === 0 && v !== endIdx) return false; // isolated, can never be visited
      if (d <= 1) deg1++;
      if (cycle && startNeighbor[v]) startReach++;
    }
    if (deg1 > 2) return false;
    if (cycle && startReach === 0) return false; // cannot close back to start

    // Connectivity: the unvisited vertices, together with the current head u
    // (which must be able to enter them), have to stay connected — otherwise a
    // whole component would be stranded. BFS from a neighbor of u.
    let seed = -1;
    for (const w of adj[u]) {
      if (!visited[w]) {
        seed = w;
        break;
      }
    }
    if (seed === -1) return false; // head cannot advance
    const seen = new Uint8Array(total);
    let sp = 0;
    stack[sp++] = seed;
    seen[seed] = 1;
    let reached = 0;
    while (sp > 0) {
      const x = stack[--sp];
      reached++;
      for (const y of adj[x]) {
        if (!visited[y] && !seen[y]) {
          seen[y] = 1;
          stack[sp++] = y;
        }
      }
    }
    return reached === remaining;
  };

  const dfs = (u: number): boolean => {
    mark(u);
    order.push(u);
    if (visitedCount === total) {
      const done = cycle ? startNeighbor[u] === 1 : u === endIdx;
      if (done) return true;
      unmark(u);
      order.pop();
      return false;
    }
    if (feasible(u)) {
      const cands = adj[u].filter((w) => !visited[w]);
      cands.sort((a, b) => (avail[a] !== avail[b] ? avail[a] - avail[b] : a - b));
      for (const w of cands) {
        // For a path, the end vertex may only be entered on the final step.
        if (!cycle && w === endIdx && visitedCount + 1 !== total) continue;
        if (dfs(w)) return true;
      }
    }
    unmark(u);
    order.pop();
    return false;
  };

  return dfs(startIdx) ? order : null;
}

/**
 * Hamilton path between `start` and `end` over a vertex set defined by an
 * adjacency function. `vertices` lists every vertex.
 */
function hamiltonPath(
  vertices: IntPerm[],
  neighborsOf: (p: IntPerm) => IntPerm[],
  start: IntPerm,
  end: IntPerm
): IntPerm[] | null {
  const { adj, index } = buildAdjacency(vertices, neighborsOf);
  const startIdx = index.get(permKey(start));
  const endIdx = index.get(permKey(end));
  if (startIdx === undefined || endIdx === undefined) return null;
  const order = runSearch(adj, startIdx, endIdx, false);
  return order ? order.map((i) => vertices[i]) : null;
}

/** Hamilton-laceable path in Π_X between two opposite-parity permutations of X. */
function laceablePath(start: IntPerm, end: IntPerm): IntPerm[] {
  const values = start.slice().sort((a, b) => a - b);
  const verts = permutationsOf(values);
  const path = hamiltonPath(verts, adjacentNeighbors, start, end);
  if (!path) {
    throw new Error(
      `No Hamilton-laceable path in Π_{${values.join(",")}} from ${start.join(
        ""
      )} to ${end.join("")}`
    );
  }
  return path;
}

/* -------------------- multiset-permutation graph G(a) --------------------- */

/** All a-permutations (label sequences over [m] with a_i copies of label i). */
function multisetVertices(a: number[]): IntPerm[] {
  const labels: number[] = [];
  for (let i = 0; i < a.length; i++) for (let c = 0; c < a[i]; c++) labels.push(i + 1);
  const seen = new Set<string>();
  const out: IntPerm[] = [];
  const used = new Array<boolean>(labels.length).fill(false);
  const cur: number[] = [];
  const rec = (): void => {
    if (cur.length === labels.length) {
      const k = permKey(cur);
      if (!seen.has(k)) {
        seen.add(k);
        out.push(cur.slice());
      }
      return;
    }
    let prev = -1;
    for (let i = 0; i < labels.length; i++) {
      if (used[i] || labels[i] === prev) continue;
      prev = labels[i];
      used[i] = true;
      cur.push(labels[i]);
      rec();
      cur.pop();
      used[i] = false;
    }
  };
  rec();
  return out;
}

/** Theorem 2.5: Hamilton path in G(a₁,a₂) from 1^a₁ 2^a₂ to 2^a₂ 1^a₁. */
function gaHamiltonPath(a1: number, a2: number): IntPerm[] {
  const verts = multisetVertices([a1, a2]);
  const start: number[] = [];
  for (let i = 0; i < a1; i++) start.push(1);
  for (let i = 0; i < a2; i++) start.push(2);
  const end: number[] = [];
  for (let i = 0; i < a2; i++) end.push(2);
  for (let i = 0; i < a1; i++) end.push(1);
  const path = hamiltonPath(verts, distinctAdjacentNeighbors, start, end);
  if (!path) {
    throw new Error(`No Hamilton path in G(${a1},${a2})`);
  }
  return path;
}

/**
 * Theorem 2.6: a Hamilton cycle of G(a) (m ≥ 3) as a cyclic vertex list whose
 * first entry is the identity a-permutation id(a) (the lexicographically least).
 */
function gaHamiltonCycle(a: number[]): IntPerm[] {
  const verts = multisetVertices(a); // verts[0] = id(a)
  const { adj } = buildAdjacency(verts, distinctAdjacentNeighbors);
  const order = runSearch(adj, 0, 0, true);
  if (!order) throw new Error(`No Hamilton cycle in G(${a.join(",")})`);
  return order.map((i) => verts[i]);
}

/* ----------------------------- Lemma 5.4 (Q) ------------------------------ */

/** Build the descending block partition of [n] for composition a. */
function blockBounds(a: number[]): { start: number[]; size: number[] } {
  const start: number[] = [];
  const size: number[] = [];
  let b = 0;
  for (let i = 0; i < a.length; i++) {
    start.push(b);
    size.push(a[i]);
    b += a[i];
  }
  return { start, size };
}

/**
 * Lemma 5.4(i): a path Q through one orbit representative per orbit of f_a (with
 * block pattern fixed to id(a)), from id = 1…n to a neighbor of f_a(id).
 * Returns the list of representative permutations (each a permutation of [n]).
 */
function buildOrbitRepPath(a: number[]): IntPerm[] {
  const m = a.length;
  const n = a.reduce((s, v) => s + v, 0);

  if (m === 1) {
    // a = (n), single odd cycle. Reps: value n fixed at the last position.
    if (n === 1) return [[1]];
    if (n === 2) return [[1, 2], [2, 1]];
    const xs: number[] = [];
    for (let v = 1; v <= n - 1; v++) xs.push(v);
    const rho: number[] = [];
    for (let v = 2; v <= n - 1; v++) rho.push(v);
    rho.push(1);
    const base = laceablePath(xs, rho); // Π_{n-1}: id → 2…(n-1)1
    return base.map((p) => [...p, n]);
  }

  const aPrime = a.slice(0, m - 1);
  const am = a[m - 1];
  const nPrime = n - am;
  const qPrime = buildOrbitRepPath(aPrime);

  if (am === 1) {
    // Block m is the single value n: append it to every representative.
    return qPrime.map((z) => [...z, n]);
  }

  // am ≥ 3: sweep block-m values with two transversals (⟨x·n⟩ and ⟨(n'+2)·x'⟩).
  const Xp: number[] = [];
  for (let v = nPrime + 1; v <= n - 1; v++) Xp.push(v);
  const px = laceablePath(
    Xp,
    [nPrime + 2, nPrime + 1, ...rangeFrom(nPrime + 3, n - 1)]
  );

  const Xpp: number[] = [nPrime + 1, ...rangeFrom(nPrime + 3, n)];
  const pp = laceablePath(
    Xpp,
    [...rangeFrom(nPrime + 3, n), nPrime + 1]
  );

  const ell = qPrime.length;
  if (ell % 2 !== 0) {
    throw new Error("Lemma 5.4 requires an even number of sub-orbits");
  }
  const out: IntPerm[] = [];
  for (let i = 0; i < ell; i++) {
    const z = qPrime[i];
    if (i < ell - 1) {
      const seg = i % 2 === 0 ? px : px.slice().reverse();
      for (const p of seg) out.push([...z, ...p, n]);
    } else {
      for (const p of pp) out.push([...z, nPrime + 2, ...p]);
    }
  }
  return out;
}

/** Inclusive integer range [lo..hi] (empty when hi < lo). */
function rangeFrom(lo: number, hi: number): number[] {
  const out: number[] = [];
  for (let v = lo; v <= hi; v++) out.push(v);
  return out;
}

/* -------------------------- Theorem 5.5 (mixing) -------------------------- */

/** Substitute block arrangements into a label sequence (the ⊗ "mix" operation). */
function mix(labelSeq: IntPerm, blockArrangements: number[][]): IntPerm {
  const counters = new Array<number>(blockArrangements.length).fill(0);
  const out: number[] = new Array(labelSeq.length);
  for (let pos = 0; pos < labelSeq.length; pos++) {
    const label = labelSeq[pos] - 1;
    out[pos] = blockArrangements[label][counters[label]++];
  }
  return out;
}

/** The single position where two permutations differ by an adjacent swap. */
function adjacentSwapPosition(p: IntPerm, q: IntPerm): number {
  let first = -1;
  for (let i = 0; i < p.length; i++) {
    if (p[i] !== q[i]) {
      if (first === -1) first = i;
      else if (i === first + 1 && p[i] === q[first] && p[first] === q[i]) {
        return first;
      } else return -1;
    }
  }
  return -1;
}

/**
 * Build the full k-symmetric Hamilton cycle of Πₙ for the chosen composition.
 * Returns the cycle as a list of permutations of [n] (length n!), in cycle
 * order, together with the realized compression factor k and composition.
 */
export function buildCompressionCycle(n: number): {
  cycle: IntPerm[];
  k: number;
  composition: number[];
} {
  if (n === 2) {
    return { cycle: [[1, 2], [2, 1]], k: 2, composition: [2] };
  }
  const a = bestOddCoprimeComposition(n);
  if (!a) throw new Error(`No valid composition for n = ${n}`);
  const m = a.length;
  const k = lcm(a);
  const { start: bStart, size: bSize } = blockBounds(a);

  // f_a: increment a value cyclically within its block.
  const nextVal = new Array<number>(n + 1).fill(0);
  for (let i = 0; i < m; i++) {
    const lo = bStart[i] + 1;
    const hi = bStart[i] + bSize[i];
    for (let v = lo; v <= hi; v++) nextVal[v] = v === hi ? lo : v + 1;
  }
  const applyFa = (p: IntPerm): IntPerm => p.map((v) => nextVal[v]);

  // Lemma 5.4: representatives Q (block pattern fixed to id(a)).
  const q = buildOrbitRepPath(a);
  // Per representative, read off the per-block arrangements.
  const ys = q.map((rep) =>
    a.map((_, i) => rep.slice(bStart[i], bStart[i] + bSize[i]))
  );

  // Theorem 5.5: build the orbit-transversal path P of length n!/k.
  let p: IntPerm[];
  if (m === 1) {
    p = q;
  } else if (m === 2) {
    const r = gaHamiltonPath(a[0], a[1]); // u0 → v
    p = [];
    for (let i = 0; i < ys.length; i++) {
      const seg = i % 2 === 0 ? r : r.slice().reverse();
      for (const w of seg) p.push(mix(w, ys[i]));
    }
  } else {
    // m ≥ 3: Theorem 2.6 Hamilton cycle of G(a); R, R' are the two Hamilton
    // paths from id(a) to its cycle-neighbors.
    const cyc = gaHamiltonCycle(a); // cyc[0] = id(a) = u0
    const len = cyc.length;
    // Forward path: u0 → cyc[1] → … → cyc[len-1] (ends at one neighbor of u0).
    const rFwd: IntPerm[] = cyc.slice();
    // Backward path: u0 → cyc[len-1] → … → cyc[1] (ends at the other neighbor).
    const rBwd: IntPerm[] = [cyc[0]];
    for (let j = len - 1; j >= 1; j--) rBwd.push(cyc[j]);

    const labelPositions = (seq: IntPerm, label: number): number[] => {
      const idx: number[] = [];
      for (let t = 0; t < seq.length; t++) if (seq[t] === label) idx.push(t);
      return idx;
    };

    p = [];
    if (ys.length % 2 !== 0) {
      throw new Error("Theorem 5.5 (m ≥ 3) requires an even orbit count");
    }
    for (let t = 0; t < ys.length; t += 2) {
      // The within-block swap connecting representatives t and t+1.
      const swapPos = adjacentSwapPosition(q[t], q[t + 1]);
      if (swapPos === -1) throw new Error("non-adjacent consecutive representatives");
      // Which block / intra-block slot does the swap touch?
      let blockOfPos = 0;
      for (let i = 0; i < m; i++) {
        if (swapPos >= bStart[i] && swapPos < bStart[i] + bSize[i]) {
          blockOfPos = i;
          break;
        }
      }
      const slot = swapPos - bStart[blockOfPos];
      const label = blockOfPos + 1;

      const works = (rPath: IntPerm[]): boolean => {
        const v = rPath[rPath.length - 1];
        const pos = labelPositions(v, label);
        return pos[slot + 1] === pos[slot] + 1;
      };
      const chosen = works(rFwd) ? rFwd : works(rBwd) ? rBwd : null;
      if (!chosen) {
        throw new Error("Theorem 5.5: neither R nor R' connects a representative pair");
      }
      for (const w of chosen) p.push(mix(w, ys[t]));
      const rev = chosen.slice().reverse();
      for (const w of rev) p.push(mix(w, ys[t + 1]));
    }
  }

  // Full cycle: C = P, f_a(P), …, f_a^{k-1}(P).
  const cycle: IntPerm[] = [];
  let layer = p;
  for (let r = 0; r < k; r++) {
    for (const x of layer) cycle.push(x);
    layer = layer.map(applyFa);
  }
  return { cycle, k, composition: a };
}

/* ----------------------------- public ordering ---------------------------- */

export type Perm = Uint8Array<ArrayBuffer>;

/**
 * Vertex ordering for the "permutahedron-compressed" preset: the maximally
 * rotationally-symmetric Hamilton cycle, as a `path` of permutations plus the
 * `flips` (adjacent-transposition generator ids, matching the permutohedron's
 * id = i+1 for swapping positions i, i+1) along the cycle.
 */
export async function permutahedronCompressionOrder(
  n: number,
  onProgress?: (done: number, total: number) => void,
  signal?: AbortSignal
): Promise<{ path: Perm[]; flips: number[] }> {
  if (signal?.aborted) throw new DOMException("Aborted", "AbortError");
  const total = factorial(n);
  onProgress?.(0, total);

  const { cycle } = buildCompressionCycle(n);

  const path: Perm[] = new Array(cycle.length);
  for (let i = 0; i < cycle.length; i++) {
    const v = new Uint8Array(n) as Perm;
    for (let j = 0; j < n; j++) v[j] = cycle[i][j];
    path[i] = v;
    if ((i + 1) % 100_000 === 0) {
      onProgress?.(i + 1, total);
      await yieldToEventLoop();
      if (signal?.aborted) throw new DOMException("Aborted", "AbortError");
    }
  }

  // The generator id for an adjacent transposition at positions (i, i+1) is i+1,
  // matching the permutohedron preset's generator ids.
  const flips: number[] = new Array(path.length);
  for (let s = 0; s < path.length; s++) {
    const next = path[(s + 1) % path.length];
    flips[s] = adjacentSwapId(path[s], next);
  }

  onProgress?.(total, total);
  return { path, flips };
}

function adjacentSwapId(p: Perm, q: Perm): number {
  for (let i = 0; i + 1 < p.length; i++) {
    if (p[i] !== q[i]) return i + 1;
  }
  return 0;
}

function yieldToEventLoop(): Promise<void> {
  return new Promise((resolve) =>
    typeof requestAnimationFrame !== "undefined"
      ? requestAnimationFrame(() => resolve())
      : setTimeout(resolve, 0)
  );
}
